### ISSUE TITLE
Student registration form

### ISSUE THREAD

**Issue by omkarkerlekar** [PaperLessEdu/schoolerp-web-ui#4]
[Student] contact information page do not contains previous button , and postal code is accepting all values , which should not. If we click on arrow button to go back the its going to the main student page,    
which is also not acceptable.
Steps to Reproduce:

Login to Application
Go to Student -> Register-->contact information
postal code is entered wrong and is accepting. no previous button int it.

Expected Result:There should be previous button , and postal code should only accept numeric values.
![contact info](https://user-images.githubusercontent.com/39027386/40227015-f5ffe954-5aaa-11e8-90e9-dc6ec359633f.jpg)

**Comment by pkhegadeedu** [comment]
- No "Previous" button on step 2 on student registration form: **Fixed** 
- If we click on arrow button to go back the its going to the main student page,
which is also not acceptable: **Expected behaviour so Not a bug for this point**
