### ISSUE TITLE
[Holiday Module]: POST api call giving bad request

### ISSUE THREAD

**Issue by pkhegadeedu** [PaperLessEdu/schoolerp-web-ui#6]
[Holiday Module]: POST api call giving bad request

Steps to Reproduce:
- Login to Application
- Go to Setup -> Holiday List
Request Payload:
{
    date: "01-01-2018",
   name: "Diwali"
}

<img width="1676" alt="screen shot 2018-05-27 at 10 52 01 pm" src="https://user-images.githubusercontent.com/37933409/40588784-9c08fb7c-6200-11e8-9888-f88792c8f247.png">

**Comment by pavanpawar4591** [comment]
starting looking at this issue

**Comment by pavanpawar4591** [comment]
curl -X POST \
  http://localhost:9090/holidays \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: c94984f5-a845-4ec4-a710-179dfefd0d75' \
  -d '{
	"name":"holi famil11y",
	"date":"2018-05-09",
	"discription":"test2222"
	
}'

get all holidays

curl -X GET \
  http://localhost:9090/holidays \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 3b80c419-4e9f-41f1-a756-e95305693219'

curl -X PUT \
  http://localhost:9090/holidays/2 \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 9526b419-ad68-4131-82d6-38112d4d512f' \
  -d '{
	"name":"holi gun",
	"date":"2018-05-12",
	"discription":"this is holiday"
	
}'



curl -X DELETE \
  http://localhost:9090/holidays/2 \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 52795898-f3bb-4cd3-a038-6dfc6aced0d5'
